replace__title: 'Example Product'
replace__body: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
  dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
  <p>Please note, if you would like to add a graphic, this will need to be uploaded in the Checkout page.</p>'
replace__url: '#'

